### ISSUE TITLE
security issue with `marked` version via `msee`

### ISSUE THREAD

**Issue by mattgodbolt** [approvals/Approvals.NodeJS#127]
Our [project](https://github.com/compiler-explorer/compiler-explorer) is getting a Dependabot alert for `marked 0.3.17` via a dependency coming from approvals@4.0.0-beta.1:

```
approvals@4.0.0-beta.1 requires marked@0.3.12 via msee@0.3.5
```

Unfortunately the `msee` issue seems to be blocked: [this issue](https://github.com/firede/msee/issues/61) was reported in 2019, and the project  hasn't been updated in over a year.

It's unlikely this is a viable attack vector (as it is used only in tests); but if there's a way to replace the `msee` dependency it would save any project that depends on `approvals` picking up the github dependabot warning.

**Comment by mattgodbolt** [comment]
On closer look it seems it's only used here:

https://github.com/approvals/Approvals.NodeJS/blob/b8920197bfe95dade9422e7d8b9930178c8cc932/bin/index.js#L19

so I _think_ it should be possible to drop in an alternative, or preprocess the help file in some way, rather than cause `msee` to be a problem on anyone who depends on `approvals`.

I see there's a number of unacknowledged PRs - is this project still being worked on or should I fork?

**Comment by staxmanade** [comment]
Hey @mattgodbolt thanks for the PR (apologies for the late reply...) 

I'll see if I can push it along...
