### ISSUE TITLE
Approvals JS and Jest

### ISSUE THREAD

**Issue by ragunathjawahar** [approvals/Approvals.NodeJS#140]
I have been using Approvals JS successfully on some of my JS projects. These were vanilla projects on the front-end. I can successfully use the tool with Mocha. However, recently I tried approvals on a React project and it did not go well because it uses Jest. I have spent sometime researching and trying out different things. The only approach that seems to work is to also have mocha installed and use the mocha binary to run the test from an external directory. If I use the mocha binary inside the same directory as the tests, it ends up creating a file with no test name.

Can you help me understand if this is the right approach. If I were to use approvals in my react project, what would be the recommended approach?

**Comment by ceilfors** [comment]
@ragunathjawahar Have you evaluated if we can do approval testing via Jest snapshot well?

**Comment by claremacrae** [comment]
Hi, Jest is now supported, and I'm using this library in a jest-based TypeScript project:
<https://github.com/obsidian-tasks-group/obsidian-tasks>

There is a template starter project that shows how to set it up:
https://github.com/approvals/ApprovalTests.TypeScript.Jest.StarterProject

It works so well I would suggest actually closing this issue.
