### ISSUE TITLE
Incorrect version tag in 6.2.1

### ISSUE THREAD

**Issue by mattgodbolt** [approvals/Approvals.NodeJS#150]
https://github.com/approvals/Approvals.NodeJS/blob/91a90b4f32dec1df45d2e0fc3a64ebf98c53433c/package.json#L4

This named tag has a `v` prefix, which means after installing, `npm outdated` thinks the installed package can be updated from `v6.2.1` to `6.2.1`:

```sh
$ npm outdated
Package        Current  Wanted  Latest  Location                    Depended by
approvals       v6.2.1   6.2.1   6.2.1  node_modules/approvals      compiler-explorer
```

I _think_ the `package.json` needs to have `6.2.1` instead of `v6.2.1` though it appears to have been published to `npm` as `6.2.1` (https://www.npmjs.com/package/approvals)

**Comment by xwipeoutx** [comment]
Saw this same thing, some sample output - you can see it's red, and doesn't want anything to do with that v

![image](https://github.com/approvals/Approvals.NodeJS/assets/1008567/4929edee-9b65-4d64-9f9a-76bd00b82f04)

**Comment by mattgodbolt** [comment]
Thanks @xwipeoutx

**Comment by mattgodbolt** [comment]
Thanks all!
