### ISSUE TITLE
Using approvals in a browser context

### ISSUE THREAD

**Issue by Hyzual** [approvals/Approvals.NodeJS#18]
Hi again !

Thanks for your quick fixes. Unfortunately, I still can't seem to figure out how to do what I originally wanted to do with approvals.

I would really like to test and refactor a browser-related JS file. To be more precise : it's an Angular file.
I cannot figure out a way to use `require()` in my Jasmine test which needs to be in a browser context so that I can use Angular.
I can see at least two solutions : 

- I can either use [browserify](http://browserify.org/) and hope that the `beforeEach()` enables me to use `this.verify()` while running tests in my browser. I've already tried doing that but I ran into issues beyond my understanding of `require()`. Apparently `browserify` doesn't like some of the paths required in Approvals. But anyway I'm not even sure if it would work at all that way, seing that we call executables on the computer from Approvals.
- Or, I need a plugin for [Karma](karma-runner.github.io), which I use to run my tests in browsers. It's running on node, so we could perfectly use `require()` in a plugin. It might work better this way. Plus since I'm using [karma-coverage](https://github.com/karma-runner/karma-coverage), I'd be able to actually see if everything is covered with my approval tests before refactoring, which really helps in being confident that everything is still going to be ok afterwards.
I could try writing it myself but I am still a total noob in NodeJS code, I'd need to properly learn before getting anything done, which will probably take weeks.

I imagine it's going to take quite some work... but then think of all the code we'd be able to refactor ! There's just so much broken, untested JS in browsers. I'll try to use approvals manually (without coverage) in the meantime.

**Comment by kristofferahl** [comment]
@Hyzual Have a look at approvals-server. Might be what you want if all you need to do is run verifications from the browser!

https://www.npmjs.com/package/approvals-server

**Comment by staxmanade** [comment]
@kristofferahl - Very cool!
