### ISSUE TITLE
Weird Namer Behavior with mocha --recursive

### ISSUE THREAD

**Issue by jamesrcounts** [approvals/Approvals.NodeJS#30]
We have some tests in subfolders

```
/test
  |- /views
  |- /zzyzx
```

When running mocha --recursive, approvals looks for all approval files under `zzyzx`

**Comment by staxmanade** [comment]
@jamesrcounts sorry I'm not sure I understand what you have setup and what you're noticing is weird about it. Can you give some extra details?

**Comment by jamesrcounts** [comment]
Yeah let me see if i can post up example code later tonight

**Comment by jamesrcounts** [comment]
Here is a [working example](https://github.com/jamesrcounts/converter).

Clone and run the tests in this repository with mocha --recursive and you should find that all approved and received files end up in `test/zzyzx`.

**Comment by staxmanade** [comment]
Thanks for the repro... interesting...

After running `mocha --recursive` I get this file structure.

```
>test
|____converter.js
|____hex
| |____hexConverter.js
|____zzyzzx
| |____Color_Code_Converter.Hex_to_RGB_conversion.converts_the_basic_colors.approved.txt
| |____Color_Code_Converter.RGB_to_Hex_conversion.converts_blue.approved.txt
| |____Color_Code_Converter.RGB_to_Hex_conversion.converts_red.approved.txt
| |____rgbConverter.js
```

but might have instead expected to see this inside the `test` folder.

```
>test
|____Color_Code_Converter.RGB_to_Hex_conversion.converts_red.approved.txt
|____converter.js
|____hex
| |____Color_Code_Converter.Hex_to_RGB_conversion.converts_the_basic_colors.approved.txt
| |____hexConverter.js
|____zzyzzx
| |____Color_Code_Converter.RGB_to_Hex_conversion.converts_blue.approved.txt
| |____rgbConverter.js
```

**Comment by jamesrcounts** [comment]
That's it exactly.
