### ISSUE TITLE
Add beyondcompare 4 support

### ISSUE THREAD

**Issue by jamesrcounts** [approvals/Approvals.NodeJS#31]
I can add a beyond compare 4 reporter, this is just a reminder for myself

**Comment by staxmanade** [comment]
~~Is beyond compare 4 different than what this supports https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Reporting/Reporters/beyondcompareReporter.js?~~ ... ba never-mind just read the code and it's only `Beyond Compare 3`..

**NOTE:** if you can think of a way to make it less version dependent, that would be awesome.

**Comment by jamesrcounts** [comment]
I had trouble getting `npm install` to complete on Windows 10.  So I've been stalled on this.  But here is a "custom" reporter that is working for us for now.

```javascript
           {
               // this is used in exception reporting etc. Just give it a name :)
               name: "BeyondCompare4",
 
                     // This is used to determine if the reporter can report on the specified file
                     // EX: an image differ vs a txt differ...
               canReportOn: function(receivedFilePath) {
                   return receivedFilePath.endsWith(".txt");
               },
 
                     // Actually execute the diff against the two files
               report: function(approved, received) {
                   if (!fs.existsSync(approved)) {
                       fs.writeFileSync(approved, "");
                   }
 
                   var exe = "C:/Program Files/Beyond Compare 4/BCompare.exe";
 
                   console.log('CMD: ' + [exe, received, approved].join(' '));
 
                   child_process.spawn(exe, [received, approved], {
                       detached: true,
                       stdio: ['pipe', 1, 2, 'ipc']
                   });
               }
           }
```

**Comment by MiguelMadero** [comment]
FYI, it works for me on mac

**Comment by staxmanade** [comment]
I've updated beyond compare reporter to try to do a little extra path searching... https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Reporting/Reporters/beyondcompareReporter.js

NOTE: I don't have this tool - so here's 🤞 that it still works (and improves on the old one)

**Comment by staxmanade** [comment]
new term 🤞 DD `crossed finger driven development`

**Comment by MiguelMadero** [comment]
:crossed_fingers: DD
