### ISSUE TITLE
Option to normalize line endings

### ISSUE THREAD

**Issue by jamesrcounts** [approvals/Approvals.NodeJS#32]
On windows, with beyond compare I often have problems with beyond compare updating the line endings in the approval file.  Since there doesn't seem to be a way to tell BC not to do this, I usually resort to writing a `normalizeLineEndings` function like this:

```js
function normalizeLineEndings(value){
        var re = new RegExp("\r?\n", "g");
        return value.replace(re, "\r\n");
}
```

It would be nice to have support for this built in so that the custom function doesn't need to be re-implemented on each project.  The ideal place would be an option passed to verifyAsJSON, since the issue comes up in that situation most often.

**Comment by staxmanade** [comment]
I've published this to npm in `v1.2.0` - let me know how it looks. (ooh, but I did so before watching CI run) here's hoping I don't have to patch :P

**Comment by jamesrcounts** [comment]
Tried it today, worked great :)

**Comment by staxmanade** [comment]
Awesome!

That task made me realize the appendEOL config is misleading.

**Comment by jamesrcounts** [comment]
One thing we observed today after updating and converting.  If you have configured this new option, and you pass an object to verify (*not* verifyAsJSON) then you get an exception in stringwriter that value.replace is not a function, which makes sense because its not a string.  

However it took a while to figure out, so maybe we could provide a nicer error message.
