### ISSUE TITLE
test errors on windows 10

### ISSUE THREAD

**Issue by staxmanade** [approvals/Approvals.NodeJS#34]
@jamesrcounts I just pulled the project on a win10 machine and ran `gulp` - seeing lots of errors (for some reason).

I didn't see any issues with `npm install` as you mentioned in #31 - what npm install errors are you seeing?

**Comment by jamesrcounts** [comment]
I just tested, and yes `npm install` is working now.  A couple hours ago I updated node on that VM from `5.1.0` to latest `5.3.0`.  

So it may have been node ver, or the combo of node ver and Win10.

**Comment by staxmanade** [comment]
Thanks @jamesrcounts 

Looking at some of the tests erroring on Win 10 - I don't understand how they're passing on the Mac. (in some cases the `.approved.txt` files are not even checked into git)... I'll keep digging

**Comment by jamesrcounts** [comment]
I do see some missing approvals.  Not sure about them.  A couple tests appear to be line ending related.  Git may be normalizing the approved file on Windows checkout.

![capture](https://cloud.githubusercontent.com/assets/1542583/11862591/b8b35698-a441-11e5-8a79-8942f25d9087.PNG)

**Comment by staxmanade** [comment]
Seems to be an issue in the directory it's saving the file to... Can't diagnose it tonight.

**Comment by staxmanade** [comment]
Some tests are designed to "fail" by not having an approval file on disk (checked in)... Closing as I just pushed a large number of commits (fixing tests and cleanup)
