### ISSUE TITLE
homeConfig is broken

### ISSUE THREAD

**Issue by martinsson** [approvals/Approvals.NodeJS#40]
the config I put in the home directory is squashed by the default config.

Seems to me that it comes from line no 75 in config.js

    var currentConfigObj = _.defaults({}, defaultConfig);

that should probably bee 

    var currentConfigObj = _.defaults({}, homeConfig, defaultConfig);
 
so that it doesn't get squashed by line no 94.

    var resultConfig = _.defaults(configOverrides || {}, currentConfigObj || {}, homeConfig, defaultConfig);

**Comment by staxmanade** [comment]
👍  Thanks for finding and fixing!!!
