### ISSUE TITLE
Reporter lookup fails on Linux

### ISSUE THREAD

**Issue by martinsson** [approvals/Approvals.NodeJS#44]
When I don't specify a reporter anywhere it selects opendiff although it doesn't exist on linux

    Error raised by reporter [opendiff]: TypeError: Bad argument

If I recall correctly I had the same behavior on macos. I'll fix soon probably but just reporting

**Comment by staxmanade** [comment]
This is likely because of the ordering of default reporters here https://github.com/approvals/Approvals.NodeJS/blob/master/lib/config.js#L15

maybe the defaults get configured differently per OS?

**Comment by staxmanade** [comment]
I originally wrote this project on Mac - and got the Windows port working (I even prototyped some stuff on Ubuntu) but Linux hasn't been a strong focus of the project. (Maybe just enough to get travis-ci to work :P)

**Comment by martinsson** [comment]
I thought that there was a selection algorithm retaining the first reporter in the config that is installed on the system. I couldn't find that in the code though. 

I tried an implementation. What do you think?

**Comment by staxmanade** [comment]
@martinsson there is a global config (if you as a developer create a file in your home directory https://github.com/approvals/Approvals.NodeJS/blob/master/lib/config.js#L75 (some notes in the readme about how to set it up manually https://github.com/approvals/Approvals.NodeJS#config-overriding)

**Comment by martinsson** [comment]
I used that, it is a nice option to have. But it is more friction than if it just works upon install, no?

**Comment by staxmanade** [comment]
sorry, I was trying to answer (maybe misunderstood)

> I thought that there was a selection algorithm retaining the first reporter in the config that is installed on the system. I couldn't find that in the code though.

I like where you're headed so far...
