### ISSUE TITLE
Consider integrating Greenkeeper

### ISSUE THREAD

**Issue by staxmanade** [approvals/Approvals.NodeJS#54]
Hey @isidore,

Looks like since I'm not an owner of the org anymore, I don't have access to add [Greenkeeper](https://github.com/integration/greenkeeper) to the project.

It's likely worthwhile to consider having more than a single person be an "owner" of this org. Thinking bus factor...

Regardless, would you mind turning on Greenkeeper? (I have no idea what that process is going to be like yet)

**Comment by isidore** [comment]
I had an other project stollen from me because of shared ownership :-( so a bit protective on that aspect. But would be happy to pair up the integrate green keeper. 
Also is only owner needed. You should have full admin privileges?

**Comment by staxmanade** [comment]
It looks like I have permission to integrate other services - but not thin one?

let me know when you're around for a pairing...
