### ISSUE TITLE
Look to add a vimdiff reporter

### ISSUE THREAD

**Issue by staxmanade** [approvals/Approvals.NodeJS#6]

**Comment by niwsa** [comment]
@staxmanade I would like to work on this,could you  provide more context?
Thanks

**Comment by staxmanade** [comment]
This would be great!

If you take a look at various reporters in this folder https://github.com/approvals/Approvals.NodeJS/tree/master/lib/Reporting/Reporters you can get an idea how other diff reporters are implemented.

Also take a look at the tests: https://github.com/approvals/Approvals.NodeJS/tree/master/test/Reporting/Reporters

Hope this helps

**Comment by niwsa** [comment]
@staxmanade I am looking at the code.Will get back to you soon on this.
Thanks

**Comment by isidore** [comment]
@kytrinyx did this in her ruby version.
https://github.com/kytrinyx/approvals/blob/794cb8b680c095f6b2266d283e99a7914af39db8/lib/approvals/reporters/launcher.rb

**Comment by niwsa** [comment]
@isidore  But does 'vimdiff' work in windows? You have to launch vim with the -d option right?

**Comment by isidore** [comment]
unsure this was focused on mac

Llewellyn Falco
www.approvaltests.com

**Comment by niwsa** [comment]
@staxmanade 
Which all platforms (UNIX/OS X/Windows) are to be supported for this reporter?

**Comment by staxmanade** [comment]
as many as you can - if you can... But if you get it working for one, that's great.

**Comment by staxmanade** [comment]
closing: https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Reporting/Reporters/vimdiffReporter.js
