### ISSUE TITLE
Optional path for Mocha approvals not working as expected

### ISSUE THREAD

**Issue by cmstead** [approvals/Approvals.NodeJS#70]
It looks like Approvals version > 1.2.x has a problem with the optional approvals file path.  My configuration setup looks like the following:

`require('approvals').configure(approvalsConfig).mocha('./test/approvals')`

However, my test failure output looks like the following:

~~~
  1) Add Export should approve stuff:
     Error: Approved file does not exist: C:\Users\cstead\Documents\projects\js-refactor\test\Add_Export.should_approve_
stuff.approved.txt:
Approved: C:\Users\cstead\Documents\projects\js-refactor\test\Add_Export.should_approve_stuff.approved.txt
Received: C:\Users\cstead\Documents\projects\js-refactor\test\Add_Export.should_approve_stuff.received.txt  1) Add Export should approve stuff:
     Error: Approved file does not exist: C:\Users\cstead\Documents\projects\js-refactor\test\Add_Export.should_approve_
stuff.approved.txt:
Approved: C:\Users\cstead\Documents\projects\js-refactor\test\Add_Export.should_approve_stuff.approved.txt
Received: C:\Users\cstead\Documents\projects\js-refactor\test\Add_Export.should_approve_stuff.received.txt
~~~

I can commit this test run in a branch on JS Refactorings for your ease of reproduction.  At any rate, I would rather not clutter up my main test folder with a mass of approval files, and I used to store everything in a ./test/approvals folder, so losing this functionality presents a hefty challenge.

Side note, I can dig in and issue a pull request if you'd like.

**Comment by cmstead** [comment]
I went ahead and just committed a branch so you can reproduce the problem as well as see the entirety of my configuration and test example.

https://github.com/cmstead/js-refactor/tree/approvalsIssue

To run the tests, clone the project, run `npm i` and then run `npm test`.

**Comment by staxmanade** [comment]
@cmstead For your issue a couple things.

1. Looks like it's an issue with this line https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Providers/BeforeEachVerifierBase.js#L14 - if the directory doesn't exist it throws and error? I'll file an issue to avoid that error going forward.
2. If you create the `./test/approvals` folder - it ran the tests for me.
3. I put a ton of work (including an updated [BeyondCompare reporter](https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Reporting/Reporters/beyondcompareReporter.js#L18) that looks for v4 into the `v2.0` release of approvals. Any chance you can grab the latest and see if it'll work for you? in your config you would change your reporters list to look like `['beyondcompare']`

**Comment by cmstead** [comment]
Sorry, I should have put an empty file in the approvals folder, git ignores empty folders, sorry about that. 

Anyway, I'll give it another go, but the thrown error wasn't the issue, (I expect to see an error thrown and I'm okay with it, and it helped me diagnose what was happening) it was where files were ending up. So strange it worked on your machine, but not mine. Maybe I just need to do a clean install of all packages. Thanks for checking it out.

**Comment by staxmanade** [comment]
Noticing that (the files are not landing in the specified directory...) I'll see what's going on.
