### ISSUE TITLE
File-based config .approvalsConfig not behaving as expected

### ISSUE THREAD

**Issue by cmstead** [approvals/Approvals.NodeJS#71]
I tried migrating my configuration to a file-based config as suggested in the docs, but it looks like my custom reporter is not recognized. I'm not clear if my format is simply wrong and the config is not Javascript or if custom reporters are not being recognized.  Perhaps the config file isn't being read? I'm just really unclear on where the actual problem lives.  Let me know what info you need to help identify the cause and I'll gather it for you.

**Comment by staxmanade** [comment]
Go ahead and share your file and describe where this file is located. Also what version of approvals are you using?

**Comment by cmstead** [comment]
I'll commit an example to the same branch as the other project and post a link here in a moment.

**Comment by cmstead** [comment]
Correction, the approvals config example is already in the branch.  Look in the root folder and you should see the .approvalsConfig file:

https://github.com/cmstead/js-refactor/tree/approvalsIssue

Also, thanks for digging into this!

**Comment by staxmanade** [comment]
ahh yea - sorry... While it's totally obvious that's how it "should" work... sadly, that's not how it does.

Issue #56 is probably what you're looking for and we haven't built that out yet...

If you want, you can copy the `.approvalsConfig` file into your "home" directory so on windows `C:/Users/yourName/.approvalsConfig` - this only fixes it for your computer.

If you feel interested in taking a stab at implementing #56 I'll be here to support it. Not sure when I'll get around to it at the moment...

**Comment by cmstead** [comment]
Sorry for the delay. I'll have a look at the issue and see what, if anything, I might be able to do. : )
