### ISSUE TITLE
Edge dependency is breaking install on Mac

### ISSUE THREAD

**Issue by cmstead** [approvals/Approvals.NodeJS#76]
Hola,

It looks like the Visual Studio reporter requires edge.  This appears to be a problem for users on Mac who can't install the edge module.  Would it make sense to extract this particular reporter to a separate module someone can add as a plugin if they need it?

Here's the associated bug in my project:

https://github.com/cmstead/js-refactor/issues/48

**Comment by cmstead** [comment]
Update, it appears there is a suggested modification which could be made.  This comes from an issue on the Edge package:

https://github.com/tjanczuk/edge/issues/593#issuecomment-353608203

Would you be open to trying the edge-js fork? I'll issue a pull request so you can try it out.

**Comment by cmstead** [comment]
Nevermind on the pull request. Apparently the tests require magic things I don't have on my machine that `npm install` doesn't provide. Sorry. : (

**Comment by staxmanade** [comment]
sorry, didn't see github notifications 😢 

Ideally we should just get rid of the `edge` dependency. I'm only using it to attempt to read some registry keys to discover visual studio https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Reporting/Reporters/visualstudioReporter.js#L19

If we could refactor and completely remove edge (maybe by now there's a decent registry nodejs library) - that would help.

**Comment by staxmanade** [comment]
I'm reviewing issues again - and looking into this.... `edge` doesn't get installed on mac or linux - it only gets installed on windows machines: https://github.com/approvals/Approvals.NodeJS/blob/master/install_dependencies.js#L7

**Comment by cmstead** [comment]
I haven't tested it in a while on my Mac, but I haven't encountered the same issues in my Linux box so this has probably sorted itself. Thanks for coming back around.
