### ISSUE TITLE
Approval approved/received location + .approvalsConfig format or example

### ISSUE THREAD

**Issue by mike03081972** [approvals/Approvals.NodeJS#79]
[approval-js-test.zip](https://github.com/approvals/Approvals.NodeJS/files/2012307/approval-js-test.zip)

Hi to all,

What is the correct format for the .approvalsConfig file ? It seems not to work !

How can I configure the location of the approved/received files ?

In my example, they goes in folder 2 but I want that the test in folder 1 stays in folder 1 and not in folder 2.

You can find attached a test project.

Thanks in advance

**Comment by mike03081972** [comment]
I have found how to set the correct location :

The call to approvals.mocha must be done inside the describe block and not outside

describe('javascript simple Approvals tests #1', function () {

    const approvals = require('approvals');

    approvals.mocha(__dirname);

    it ('hello world', function () {

        const value = 'HELLO WORLD';

        this.verify(value);
    });

});

**Comment by staxmanade** [comment]
Nice - I actually don't like the mocha integration - because of this scoping issue... I'm glad you figured something out for you need.
