### ISSUE TITLE
Issues with Buffer Compare Loop

### ISSUE THREAD

**Issue by CaptainMcCurry** [approvals/Approvals.NodeJS#86]
When verifying data we run into false positives when the string remains the same but new data is added to the end of the string, this is happening with node code and can easily be reproduced using the CLI tool.

If the approval matches the first call below (below), it will also match the second call in this example:

echo 'Hello World!' | approvals helloWorldTest --reporter gitdiff --outdir .
echo 'Hello World!2' | approvals helloWorldTest --reporter gitdiff --outdir .

We were able to produce the expected result by adding the following to the FileApprover.js:

    // if( approvedFileBuffer.length !== receivedFileBuffer.length)
    // {
    //     throwReporterError("Files do not match");
    // }

**Comment by staxmanade** [comment]
Nice - just saw this issue. Thanks for reporting. Will take a look soon

**Comment by staxmanade** [comment]
@CaptainMcCurry Thanks for reporting this issue - sorry it took so long to incorporate. Hope this helps.

**Comment by CaptainMcCurry** [comment]
Thank you! I will check it out!
