### ISSUE TITLE
event-stream flatmap-stream

### ISSUE THREAD

**Issue by cuzzlor** [approvals/Approvals.NodeJS#87]
When I install v3.0.3 I get:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for flatmap-stream@^0.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'event-stream'
npm ERR! notarget
```

Looks like the referenced version of event-stream has a dependency on the removed (malicious) flatmap-stream package perhaps.

Could you pls update the referenced version of event-stream?

PS - thanks for fixing the null value bug with the key ordering code.

**Comment by staxmanade** [comment]
Thanks for reporting - I'll take a peek soon...

> PS - thanks for fixing the null value bug with the key ordering code.

ha - yea I ran into it the other day and was like "how did that ever not get caught -- oops"

**Comment by staxmanade** [comment]
@cuzzlor can you try the latest release?
